name: CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (use the version specified in package.json)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run Prettier (format check)
      - name: Run Prettier
        run: npm run format

      # Step 6: Build the project
      - name: Build the project
        run: npm run build

      # Step 7: (Optional) Run tests if you have any
      # - name: Run tests
      #   run: npm run test
