name: CI Workflow

on:
  workflow_dispatch:
    inputs:
      version_increment:
        description: 'Version increment type'
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - patch
          - minor
          - major
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'
      - 'CHANGELOG.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: npm run build

  publish:
    needs: build-and-test
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.version_increment != 'none'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Update version
        id: version
        run: |
          git pull origin main
          NEW_VERSION=$(npm version ${{ github.event.inputs.version_increment }} -m "Release %s [skip ci]")
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Push changes
        run: git push origin main --follow-tags

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh release create ${{ steps.version.outputs.new_version }} \
            --title "Release ${{ steps.version.outputs.new_version }}" \
            --notes "Please see CHANGELOG.md for details"
